import geolocation.js;

/*
Early implementation of user class. The ID parameter must be generated at time
of instantiation by outside function that generates random integer and checks
that integer against array of active IDs on the web application. The screenName
parameter is similar as a random predetermined name must be taken from an array
and checked against an array of active names, then assigned to the name var.
The pos parameter is generated by the geolocation class. Calling the getLocation
function returns a position object that can be assigned to the user. This contains
the users coordinates.
*/
function user(ID, screenName, pos) {
  var uniqueID;
  var name;
  var position;

  uniqueID = ID;

  name = screenName;

  position = pos;
}
